sudo: required
addons:
  apt:
    update: true
env:
  global:
  - OPENSHIFT_VERSION=3.9.0
  - OPENSHIFT_COMMIT=191fece
  - DOCKER_USER=whaitukay+bot
  - secure:  XjZNRUkz+qToOJwUNFJCWF/tBeFIwfSds/QeLQnWbxnJQVcWJXDZogREkynxUj9cmTzpdqxodHA4Dtr7n60ok1kiP8CI+p/cM5Wsd3N4qOm6AehNdpNs4hqGf9+0oF+Uj0skuqYZqkdgQqwR2uIGCoy6K4Zg6QyfkGL6WM6hB+xjiqJGr5l6a0ep8ybNijGOx7qz30UMVxQakRWXlRiXAIy/DfV1/IPmHIOjXUC8i8roku6zYKlJ6pMOdrMneLFOo0xh1r0TdijQkVRCN4mXdBHY+Ufx6b9EQ5TLcL+AtAwWE/bwvVqLd4XVDeb6Lf897X8Zud1MXiimAFDBcO2C2yFy+zZgLVUBQ0w7nOFndP2DoiVC+yWtBAWqDkHznaQY9LDPFdL/4GUsk9+1OVLK7b/7HF4fA6zsVcT7glmUcWd4d2QITf+WaR0i6kDw2fUOqBzjoBTMr3FSSO2USjc6zzqS0feat1oZUYPWELD6ALI45p1YYL2SpxjNYBFaqRoFI2+VllOw2Bma1zq8g+DoIzCxXb3M2WdLSU13s2uSddPcJCy0YvmEL8Dr+6FeRRRS2MPH8Om2IhAICaS1fot5iDeUNdbc/fbC55yjVKlaZNitlw90Z6q2Um7PtS7/yRHZ4iM8AJ/KgpcC5Gbl1HnpWgA7SS/DsirOBaCwtB/2J3k=
  matrix:
  - OPENSHIFT_TEMPLATE=template.yml
  - OPENSHIFT_TEMPLATE=persistent-template.yml
services:
- docker
before_install:
- "./tools/travis/setupscan.sh"
- "./tools/travis/setup.sh"
script:
- "./tools/travis/scancode.sh"
- ./tools/travis/build.sh "WHAITUKAY_VERSION=openshift-travis-testing WHISK_ACTIONS_INVOKES_CONCURRENT=1000"
- "./tools/travis/test.sh"
after_failure:
- "./tools/travis/collect-logs.sh"
stages:
- docker build
- test
- deploy
jobs:
  include:
  - stage: docker build
    env: OPENSHIFT_TEMPLATE=template.yml
    before_install: skip
    script: "./tools/travis/publish.sh openshift-travis-testing"
  - stage: deploy
    env: OPENSHIFT_TEMPLATE=template.yml
    before_install: skip
    script: "./tools/travis/publish.sh"
