sudo: required
addons:
  apt:
    update: true
env:
  global:
  - OPENSHIFT_VERSION=3.9.0
  - OPENSHIFT_COMMIT=191fece
  - DOCKER_USER=whaitukay+bot
  - secure: HHLy8eDUZhqGjxDhH5KpoXStsxzE6nGWkSfeL4zUQotxfci5KD0e00QaYs2LXRxZH+wMPzN8vUPC1TZWQM/LV03EK8pd1SVMnext8JifQqIYSIaPqgGA9tJ2yprLTuLkICJCWqGP7RLPt4PvgAXfvV1+trtA5p/38YUtx7nIirwaMAl8uZVM/xyf+zgq18il4hY4L1Vhk+WwXCRRwdYdExMqObBckvPUjx4qURSYgmcKxwcC/bYYMCh2KPkRF7zcWusgbt48Ck5VeEw3GdQK/54lnjjZFhVQwWTH7KBHJr25D/LbCGpKia6YRgBtQGRr5sdMUH7AubICbsImiMtiU3iDRzMrzNy5v3pDtBSh1MkTZ1KUxAATkoGN9pDDxRxyrJhRP1u2amzhXvXb6b1JqGMzWr7kbAdrP6rqfoEH4qgJ3rHJy6ba4ah8N4zaAn5VIwHWtyIJCt6lihe+jnJNrYVBNTKiIMdfSWmJfc6EvzCcQ2mkGmG+QYNqzJuTncOTL/gWUN7p17Eqiw67pXr8TqX5cxjR/GlnCmy1yqBfhOioglGu3dIIld7xwiA06VVcHtT3lbTEmES9wv4C1eoBpE9ri3KsvPqw2kTRyjaomRiaxKcYa9r4zsftT2cXlLCj888wnvSpNwoKZknQiF+L3/ODxvLapU4SabFVM2OJ9rU=
  matrix:
  - OPENSHIFT_TEMPLATE=template.yml
  - OPENSHIFT_TEMPLATE=persistent-template.yml

services:
- docker
before_install:
- "./tools/travis/setupscan.sh"
- "./tools/travis/setup.sh"
script:
- "./tools/travis/scancode.sh"
- ./tools/travis/build.sh "WHAITUKAY_VERSION=openshift-travis-testing WHISK_ACTIONS_INVOKES_CONCURRENT=1000"
- "./tools/travis/test.sh"
after_failure:
- "./tools/travis/collect-logs.sh"
stages:
- docker build
- test
- deploy
jobs:
  include:
  - stage: docker build
    env: OPENSHIFT_TEMPLATE=template.yml
    before_install: skip
    script: "./tools/travis/publish.sh openshift-travis-testing"
  - stage: deploy
    env: OPENSHIFT_TEMPLATE=template.yml
    before_install: skip
    script: "./tools/travis/publish.sh"
